import React, { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  en: {
    chooseLanguage: 'Choose Language',
    selectLanguage: 'Please select your preferred language',
    continue: 'Continue',
    changeLanguage: 'Change Language',
    setLanguage: 'Set Language',
    login: 'Login',
    signup: 'Sign Up',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    role: 'Role',
    public: 'Public',
    counsellor: 'Counsellor',
    tutor: 'Tutor',
    admin: 'Admin',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    newUser: 'New user?',
    signUpWithGoogle: 'Sign Up with Google',
    signInWithGoogle: 'Sign in with Google',
    loginWithGoogle: 'Login with Google',
    invalidCredentials: 'Invalid credentials',
    bannedAccount: 'Your account has been banned. Reason',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    lightnessForMind: 'Lightness for the mind',
    yourProfile: 'Your Profile',
    fullName: 'Full Name',
    emailPrimary: 'Email (Primary)',
    phoneNumber: 'Phone Number',
    education: 'Education',
    hospitalName: 'Hospital/Clinic Name',
    yearsOfExperience: 'Years of Experience',
    country: 'Country',
    state: 'State',
    city: 'City',
    basicBio: 'Basic Bio',
    submitChanges: 'Submit Changes',
    contactInfo: 'Contact info',
    academicBackground: 'Academic background',
    whereDoYouPractice: 'Where do you practice?',
    experienceExample: 'e.g. 10+ years',
    selectCountry: 'Select Country',
    selectState: 'Select State',
    selectCity: 'Select City',
    bioPlaceholder: 'A brief bit about you...',
    about: 'About',
    aiCompanion: 'AI Companion',
    peerForum: 'Peer Forum',
    bookCounsellor: 'Book a Counsellor',
    videos: 'Videos',
    libraryOfWisdom: 'Library of Wisdom',
    classesAndEvents: 'Classes & Events',
    appointments: 'Appointments',
    publicUsers: 'Public users',
    counsellors: 'Counsellors',
    tutors: 'Tutors',
    complaintsAndReports: 'Complaints and Reports',
    profile: 'Profile',
    reportIssue: 'Report Issue',
    notifications: 'Notifications',
    clearAll: 'Clear All',
    noNotifications: 'No new notifications',
    logout: 'Logout',
    back: 'Back',
    ourVision: 'Our Vision',
    ourMission: 'Our Mission',
    whatWeOffer: 'What We Offer',
    lightnessForMindTitle: 'Lightness for the mind'
  },
  ta: {
    chooseLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    selectLanguage: 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
    continue: 'தொடரவும்',
    changeLanguage: 'மொழி மாற்றவும்',
    setLanguage: 'மொழியை அமைக்கவும்',
    login: 'உள்நுழைவு',
    signup: 'பதிவுசெய்',
    name: 'பெயர்',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    role: 'பங்கு',
    public: 'பொது',
    counsellor: 'ஆலோசகர்',
    tutor: 'பயிற்றுநர்',
    admin: 'நிர்வாகி',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    loginHere: 'இங்கே உள்நுழைக',
    newUser: 'புதிய பயனர்?',
    signUpWithGoogle: 'கூகிள் மூலம் பதிவுசெய்',
    signInWithGoogle: 'கூகிள் மூலம் உள்நுழைக',
    loginWithGoogle: 'கூகிள் மூலம் உள்நுழைக',
    invalidCredentials: 'தவறான அங்கீகார விவரங்கள்',
    bannedAccount: 'உங்கள் கணக்குத் தடைசெய்யப்பட்டுள்ளது. காரணம்',
    showPassword: 'கடவுச்சொல்லை காண்பி',
    hidePassword: 'கடவுச்சொல்லை மறை',
    lightnessForMind: 'மனதிற்கான ஒளிமை',
    yourProfile: 'உங்கள் சுயவிவரம்',
    fullName: 'முழு பெயர்',
    emailPrimary: 'மின்னஞ்சல் (முதன்மை)',
    phoneNumber: 'தொலைபேசி எண்',
    education: 'கல்வி',
    hospitalName: 'மருத்துவமனை/மருத்துவமனத்தின் பெயர்',
    yearsOfExperience: 'அனுபவ ஆண்டுகள்',
    country: 'நாடு',
    state: 'மாநிலம்',
    city: 'நகரம்',
    basicBio: 'அடிப்படை வாழ்க்கைப் பின்னணி',
    submitChanges: 'மாற்றங்களை சமர்ப்பிக்கவும்',
    contactInfo: 'தொடர்பு தகவல்',
    academicBackground: 'கல்விச் பின்னணி',
    whereDoYouPractice: 'நீங்கள் எங்கு பயிற்சி பெறுகிறீர்கள்?',
    experienceExample: 'உதாரணம்: 10+ ஆண்டுகள்',
    selectCountry: 'நாட்டைத் தேர்ந்தெடுக்கவும்',
    selectState: 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    selectCity: 'நகரத்தைத் தேர்ந்தெடுக்கவும்',
    bioPlaceholder: 'உங்களைப் பற்றிய ஒரு சிறிய விவரம்...',
    about: 'பற்றி',
    aiCompanion: 'ஏ.ஐ. தோழன்',
    peerForum: 'இணையான மன்றம்',
    bookCounsellor: 'ஆலோசகரை பதிவு செய்',
    videos: 'வீடியோக்கள்',
    libraryOfWisdom: 'அறிவின் அகராதி',
    classesAndEvents: 'வகுப்புகள் மற்றும் நிகழ்வுகள்',
    appointments: 'நியமனங்கள்',
    publicUsers: 'பொது பயனர்கள்',
    counsellors: 'ஆலோசகர்கள்',
    tutors: 'பயிற்றுநர்கள்',
    complaintsAndReports: 'புகார்கள் மற்றும் அறிக்கைகள்',
    profile: 'சுயவிவரம்',
    reportIssue: 'பிரச்சனையை புகார் செய்',
    notifications: 'அறிவிப்புகள்',
    clearAll: 'அனைத்தையும் அழி',
    noNotifications: 'புதிய அறிவிப்புகள் எதுவும் இல்லை',
    logout: 'வெளியேறு',
    back: 'பின்செல்',
    ourVision: 'எங்கள் பார்வை',
    ourMission: 'எங்கள் நோக்கம்',
    whatWeOffer: 'நாம் வழங்குவது',
    lightnessForMindTitle: 'மனதிற்கான ஒளிமை'
  },
  hi: {
    chooseLanguage: 'भाषा चुनें',
    selectLanguage: 'कृपया अपनी पसंदीदा भाषा चुनें',
    continue: 'जारी रखें',
    changeLanguage: 'भाषा बदलें',
    setLanguage: 'भाषा सेट करें',
    login: 'लॉगिन',
    signup: 'साइन अप',
    name: 'नाम',
    email: 'ईमेल',
    password: 'पासवर्ड',
    role: 'भूमिका',
    public: 'पब्लिक',
    counsellor: 'काउंसलर',
    tutor: 'ट्यूटर',
    admin: 'एडमिन',
    alreadyHaveAccount: 'पहले से खाता है?',
    loginHere: 'यहां लॉगिन करें',
    newUser: 'नया उपयोगकर्ता?',
    signUpWithGoogle: 'गूगल के साथ साइन अप करें',
    signInWithGoogle: 'गूगल के साथ साइन इन करें',
    loginWithGoogle: 'गूगल के साथ लॉगिन करें',
    invalidCredentials: 'अमान्य प्रमाणपत्र',
    bannedAccount: 'आपका खाता प्रतिबंधित कर दिया गया है। कारण',
    showPassword: 'पासवर्ड दिखाएं',
    hidePassword: 'पासवर्ड छिपाएं',
    lightnessForMind: 'मन के लिए हल्कापन',
    yourProfile: 'आपकी प्रोफ़ाइल',
    fullName: 'पूरा नाम',
    emailPrimary: 'ईमेल (प्राथमिक)',
    phoneNumber: 'फ़ोन नंबर',
    education: 'शिक्षा',
    hospitalName: 'अस्पताल/क्लिनिक का नाम',
    yearsOfExperience: 'अनुभव के वर्ष',
    country: 'देश',
    state: 'राज्य',
    city: 'शहर',
    basicBio: 'मूल बायो',
    submitChanges: 'परिवर्तन सबमिट करें',
    contactInfo: 'संपर्क जानकारी',
    academicBackground: 'शैक्षिक पृष्ठभूमि',
    whereDoYouPractice: 'आप कहाँ अभ्यास करते हैं?',
    experienceExample: 'उदा. 10+ वर्ष',
    selectCountry: 'देश चुनें',
    selectState: 'राज्य चुनें',
    selectCity: 'शहर चुनें',
    bioPlaceholder: 'आपके बारे में संक्षिप्त जानकारी...',
    about: 'के बारे में',
    aiCompanion: 'एआई साथी',
    peerForum: 'साथी मंच',
    bookCounsellor: 'एक काउंसलर बुक करें',
    videos: 'विडियो',
    libraryOfWisdom: 'ज्ञान पुस्तकालय',
    classesAndEvents: 'कक्षाएं और कार्यक्रम',
    appointments: 'नियुक्तियाँ',
    publicUsers: 'सामान्य उपयोगकर्ता',
    counsellors: 'सलाहकार',
    tutors: 'ट्यूटर',
    complaintsAndReports: 'शिकायतें और रिपोर्टें',
    profile: 'प्रोफ़ाइल',
    reportIssue: 'समस्या रिपोर्ट करें',
    notifications: 'सूचनाएं',
    clearAll: 'सब साफ़ करें',
    noNotifications: 'कोई नई सूचनाएं नहीं',
    logout: 'लॉग आउट',
    back: 'वापस',
    ourVision: 'हमारी दृष्टि',
    ourMission: 'हमारा मिशन',
    whatWeOffer: 'हम जो पेश करते हैं',
    lightnessForMindTitle: 'मन के लिए हल्कापन'
  },
  kn: {
    chooseLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    selectLanguage: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಚ್ಛಿತ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    continue: 'ಮುಂದೆ',
    changeLanguage: 'ಭಾಷೆಯನ್ನು ಬದಲಿಸು',
    setLanguage: 'ಭಾಷೆಯನ್ನು ನಿರ್ಧರಿಸಿ',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    name: 'ಹೆಸರು',
    email: 'ಇಮೇಲ್',
    password: 'ಗುಪ್ತಪದ',
    role: 'ಭೂಮಿಕೆ',
    public: 'ಸಾರ್ವಜನಿಕ',
    counsellor: 'ಮಾರ್ಗದರ್ಶಕ',
    tutor: 'ಗುರು',
    admin: 'ನಿರ್ವಾಹಕ',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆಯಿದೆ?',
    loginHere: 'ಇಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ',
    newUser: 'ಹೊಸ ಬಳಕೆದಾರರು?',
    signUpWithGoogle: 'ಗೂಗಲ್‌ನೊಂದಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    signInWithGoogle: 'ಗೂಗಲ್‌ನೊಂದಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    loginWithGoogle: 'ಗೂಗಲ್‌ನೊಂದಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
    invalidCredentials: 'ಅಮಾನ್ಯ ಪ್ರವೇಶ ವಿವರಗಳು',
    bannedAccount: 'ನಿಮ್ಮ ಖಾತೆಯನ್ನು ತಡೆಯಿಸಲಾಗಿದೆ. ಕಾರಣ',
    showPassword: 'ಗುಪ್ತಪದವನ್ನು ತೋರಿಸಿ',
    hidePassword: 'ಗುಪ್ತಪದವನ್ನು ಮರೆಮಾಡಿ',
    lightnessForMind: 'ಮನಸ್ಸಿಗಾಗಿ ಬೆಳಕು',
    yourProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    emailPrimary: 'ಇಮೇಲ್ (ಪ್ರಾಥಮಿಕ)',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    education: 'ಶಿಕ್ಷಣ',
    hospitalName: 'ಆಸ್ಪತ್ರೆ / ಕ್ಲಿನಿಕ್ ಹೆಸರು',
    yearsOfExperience: 'ಅನುಭವದ ವರ್ಷಗಳು',
    country: 'ದೇಶ',
    state: 'ರಾಜ್ಯ',
    city: 'ನಗರ',
    basicBio: 'ಮೂಲ ಜೀವನಚರಿತ್ರೆ',
    submitChanges: 'ಮಾರ್ಪುಗಳನ್ನು ಸಲ್ಲಿಸಿ',
    contactInfo: 'ಸಂಪರ್ಕ ಮಾಹಿತಿ',
    academicBackground: 'ವಿದ್ಯಾಭ್ಯಾಸ ಹಿನ್ನೆಲೆ',
    whereDoYouPractice: 'ನೀವು ಎಲ್ಲಿಗೆ ಅಭ್ಯಾಸ ಮಾಡುತ್ತೀರಿ?',
    experienceExample: 'ಉದಾ. 10+ ವರ್ಷಗಳು',
    selectCountry: 'ದೇಶ ಆಯ್ಕೆಮಾಡಿ',
    selectState: 'ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ',
    selectCity: 'ನಗರ ಆಯ್ಕೆಮಾಡಿ',
    bioPlaceholder: 'ನಿಮ್ಮ ಬಗ್ಗೆ ಸಂಕ್ಷಿಪ್ತ ಮಾಹಿತಿ...',
    about: 'ಬಗ್ಗೆ',
    aiCompanion: 'ಎಐ ಸಹಚರ',
    peerForum: 'ಸಹೋದ್ಯೋಗಿ ವೇದಿಕೆ',
    bookCounsellor: 'ಮಾರ್ಗದರ್ಶಕನನ್ನು ಬುಕ್ ಮಾಡಿ',
    videos: 'ವೀಡಿಯೋಗಳು',
    libraryOfWisdom: 'ಜ್ಞಾನ ಗ್ರಂಥಾಲಯ',
    classesAndEvents: 'ತರಗತಿಗಳು ಮತ್ತು ಕಾರ್ಯಕ್ರಮಗಳು',
    appointments: 'ನಿಯೋಜನೆಗಳು',
    publicUsers: 'ಸಾರ್ವಜನಿಕ ಬಳಕೆದಾರರು',
    counsellors: 'ಮಾರ್ಗದರ್ಶಕರು',
    tutors: 'ಟ್ಯೂಟರ್ಸ್',
    complaintsAndReports: 'ಏಳೆಯುಗಳು ಮತ್ತು ವರದಿಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    reportIssue: 'ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    clearAll: 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    noNotifications: 'ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳು ಇಲ್ಲ',
    logout: 'ಲಾಗ್ ಔಟ್',
    back: 'ಹಿಂದಕ್ಕೆ',
    ourVision: 'ನಮ್ಮ ದೃಷ್ಟಿ',
    ourMission: 'ನಮ್ಮ ಗುರಿ',
    whatWeOffer: 'ನಾವು ನೀಡುವದು',
    lightnessForMindTitle: 'ಮನಸ್ಸಿಗಾಗಿ ಬೆಳಕು'
  },
  te: {
    chooseLanguage: 'భాషను ఎంచుకోండి',
    selectLanguage: 'దయచేసి మీ ఇష్టమైన భాషను ఎంచుకోండి',
    continue: 'కొనసాగించండి',
    changeLanguage: 'భాషని మార్చు',
    setLanguage: 'భాషని సెట్ చేయండి',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    name: 'పేరు',
    email: 'ఇమెయిల్',
    password: 'పాస్వర్డ్',
    role: 'పాత్ర',
    public: 'ప్రజా',
    counsellor: 'సలహాదారు',
    tutor: 'పర్యవేక్షకుడు',
    admin: 'అడ్మిన్',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    loginHere: 'ఇక్కడ లాగిన్ అవ్వండి',
    newUser: 'కొత్త యూజర్?',
    signUpWithGoogle: 'గూగుల్‌తో సైన్ అప్ చేయండి',
    signInWithGoogle: 'గూగుల్‌తో సైన్ ఇన్ చేయండి',
    loginWithGoogle: 'గూగుల్‌తో లాగిన్ అవ్వండి',
    invalidCredentials: 'చెల్లని గుర్తింపు వివరాలు',
    bannedAccount: 'మీ ఖాతా బ్యాన్ చేయబడింది. కారణం',
    showPassword: 'పాస్వర్డ్ చూపించు',
    hidePassword: 'పాస్వర్డ్ దాచు',
    lightnessForMind: 'మనసుకు తేలిక',
    yourProfile: 'మీ ప్రొఫైల్',
    fullName: 'పూర్తి పేరు',
    emailPrimary: 'ఈమెయిల్ (ప్రాథమిక)',
    phoneNumber: 'ఫోన్ నంబర్',
    education: 'విద్య',
    hospitalName: 'ఆసుపత్రి/క్లినిక్ పేరు',
    yearsOfExperience: 'అనుభవ సంవత్సరాలు',
    country: 'దేశం',
    state: 'రాష్ట్రం',
    city: 'నగరం',
    basicBio: 'ప్రాథమిక బయో',
    submitChanges: 'మార్పులను సబ్మిట్ చేయండి',
    contactInfo: 'సంప్రదింపుల సమాచారం',
    academicBackground: 'అకాడెమిక్ నేపథ్యం',
    whereDoYouPractice: 'మీరు ఎక్కడ ప్రాక్టీస్ చేస్తారు?',
    experienceExample: 'ఉదా. 10+ సంవత్సరాలు',
    selectCountry: 'దేశాన్ని ఎంచుకోండి',
    selectState: 'రాష్ట్రాన్ని ఎంచుకోండి',
    selectCity: 'నగరాన్ని ఎంచుకోండి',
    bioPlaceholder: 'మీ గురించి సంక్షిప్తంగా...',
    about: 'గురించి',
    aiCompanion: 'ఏఐ సహచరుడు',
    peerForum: 'పియర్ ఫోరం',
    bookCounsellor: 'సలహాదారును బుక్ చేయండి',
    videos: 'వీడియోలు',
    libraryOfWisdom: 'జ్ఞాన గ్రంథాలయం',
    classesAndEvents: 'తరగతులు & ఈవెంట్స్',
    appointments: 'అపాయింట్‌మెంట్లు',
    publicUsers: 'ప్రజా వినియోగదారులు',
    counsellors: 'సలహాదారులు',
    tutors: 'ట్యూటర్లు',
    complaintsAndReports: 'ఫిర్యాదులు మరియు నివేదికలు',
    profile: 'ప్రొఫైల్',
    reportIssue: 'సమస్యను నివేదించండి',
    notifications: 'నోటిఫికేషన్లు',
    clearAll: 'అన్నిటిని క్లియర్ చేయండి',
    noNotifications: 'కొత్త నోటిఫికేషన్లు లేవు',
    logout: 'లాగౌట్',
    back: 'వెనుక',
    ourVision: 'మా దృష్టి',
    ourMission: 'మా లక్ష్యం',
    whatWeOffer: 'మేము అందించేవి',
    lightnessForMindTitle: 'మనసుకు తేలిక'
  },
  ml: {
    chooseLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    selectLanguage: 'ദയവായി നിങ്ങളുടെ ഇഷ്ടപ്പെടുന്ന ഭാഷ തിരഞ്ഞെടുക്കുക',
    continue: 'തുടരുക',
    changeLanguage: 'ഭാഷ മാറ്റുക',
    setLanguage: 'ഭാഷ സജ്ജമാക്കുക',
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    name: 'പേര്',
    email: 'ഇമെയിൽ',
    password: 'പാസ്വേഡ്',
    role: 'പങ്ക്',
    public: 'പൊതു',
    counsellor: 'സലഹാവർ',
    tutor: 'ട്യൂട്ടർ',
    admin: 'അഡ്മിൻ',
    alreadyHaveAccount: 'ഇപ്പോൾ തന്നെ അക്കൗണ്ട് ഉണ്ടോ?',
    loginHere: 'ഇവിടെ ലോഗിൻ ചെയ്യുക',
    newUser: 'പുതിയ ഉപയോക്താവോ?',
    signUpWithGoogle: 'ഗൂഗിൾ ഉപയോഗിച്ച് സൈൻ അപ്പ് ചെയ്യുക',
    signInWithGoogle: 'ഗൂഗിൾ ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക',
    loginWithGoogle: 'ഗൂഗിൾ ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക',
    invalidCredentials: 'അസാധുവായ സാക്ഷ്യപത്രങ്ങൾ',
    bannedAccount: 'നിങ്ങളുടെ അക്കൗണ്ട് തടഞ്ഞിരിക്കുന്നു. കാരണം',
    showPassword: 'പാസ്‌വേഡ് കാണിക്കുക',
    hidePassword: 'പാസ്‌വേഡ് മറയ്ക്കുക',
    lightnessForMind: 'മനസ്സിന്‍റെ ലഘുത',
    yourProfile: 'നിങ്ങളുടെ പ്രൊഫൈൽ',
    fullName: 'പൂർണ്ണ പേര്',
    emailPrimary: 'ഇമെയിൽ (പ്രാഥമിക)',
    phoneNumber: 'ഫോൺ നമ്പർ',
    education: 'വിദ്യാഭ്യാസം',
    hospitalName: 'ആസ്പത്രി/ക്ലിനിക് പേര്',
    yearsOfExperience: 'അനുഭവ വർഷങ്ങൾ',
    country: 'രാജ്യം',
    state: 'സംസ്ഥാനം',
    city: 'നഗരം',
    basicBio: 'അടിസ്ഥാന ബയോ',
    submitChanges: 'മാറ്റങ്ങൾ സമർപ്പിക്കുക',
    contactInfo: 'സമ്പർക്ക വിവരം',
    academicBackground: 'അക്കാദമിക് പശ്ചാത്തലം',
    whereDoYouPractice: 'നിങ്ങൾ എവിടെയാണ് പ്രാക്ടീസ് ചെയ്യുന്നത്?',
    experienceExample: 'ഉദാ. 10+ വർഷം',
    selectCountry: 'രാജ്യം തിരഞ്ഞെടുക്കുക',
    selectState: 'സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
    selectCity: 'നഗരം തിരഞ്ഞെടുക്കുക',
    bioPlaceholder: 'നിങ്ങളെക്കുറിച്ചുള്ള ചെറിയ വിവരങ്ങൾ...',
    about: 'കുറിച്ച്',
    aiCompanion: 'AI കൂട്ടുകാരൻ',
    peerForum: 'പിയർ ഫോറം',
    bookCounsellor: 'സലഹാകാരനെ ബുക്ക് ചെയ്യുക',
    videos: 'വീഡിയോകൾ',
    libraryOfWisdom: 'വിദ്വത്സ്ഥിതി ഗ്രന്ഥശാല',
    classesAndEvents: 'ക്ലാസുകളും ഇവന്റുകളും',
    appointments: 'നിയമനങ്ങൾ',
    publicUsers: 'പൊതു ഉപയോക്താക്കൾ',
    counsellors: 'സലഹാകാർ',
    tutors: 'ട്യുട്ടേഴ്‌സ്',
    complaintsAndReports: 'പരാതികളും റിപ്പോർട്ടുകളും',
    profile: 'പ്രൊഫൈൽ',
    reportIssue: 'പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക',
    notifications: 'അറിയിപ്പുകൾ',
    clearAll: 'എല്ലാം ക്ലിയർ ചെയ്യുക',
    noNotifications: 'പുതിയ അറിയിപ്പുകൾ ഒന്നുമില്ല',
    logout: 'ലോഗൗട്ട്',
    back: 'മടങ്ങി',
    ourVision: 'ഞങ്ങളുടെ ദർശനം',
    ourMission: 'ഞങ്ങളുടെ ദൗത്യം',
    whatWeOffer: 'നാം നൽകുന്നത്',
    lightnessForMindTitle: 'മനസ്സിന്‍റെ ലഘുത'
  }
};

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => { },
  t: (key) => translations.en[key] || key
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const stored = localStorage.getItem('userLanguage');
    return stored || 'en';
  });

  useEffect(() => {
    localStorage.setItem('userLanguage', language);
  }, [language]);

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
